name: Ejemplo_windows-latest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: my-step
        run: echo "Hello World...MASTER !"
