name: Ejemplo_ubuntu-latest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World...MASTER !"
