name: Demo_Maven
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
 test: 
  runs-on: windows-latest
  
  steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 16
    uses: actions/setup-java@v2
   
    with:
      java-version: '16'  
      distribution: 'temurin'
      cache: maven

  - name: Build with Maven
    run: mvn test -DsuiteFile="testng.xml"
