name: demo
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        #distribution: 'temurin'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file testng.xml
      #run: mvn clean test -Dsurefire.suiteXmlFiles=/path/to/testng.xml
      run: mvn -B package --file pom.xml
