name: Ejemplo_windows-latest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@V2
      - name: step_Ejemplo_windows-latest
        run: echo "Hello World...MASTER !"
