name: Ejemplo_ubuntu-latest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@V3
      - name: step_Ejemplo_ubuntu-latest
        run: echo "Hello World...MASTER !"
